#
# Operating System Wrapper for POSIX systems
#

import os
import signal


MPLAYER = "mplayer"


def Quote(s):
    return "'" + s.replace ("'", r"'\''") + "'"


def Kill (pid):
    os.kill (pid, signal.SIGTERM)


def GenScriptPlay (opts):
    return u"""#!/bin/sh
# This file has been generated by TinyAVI

mplayer %(opts)s -noaspect %(input)s 2>&1
""" %opts


def GenScriptEncode (opts):
    return u"""#!/bin/sh
# This file has been generated by TinyAVI

echo "-= STAGE 1 =-"
nice mencoder %(pass1opts)s %(input)s -o /dev/null 2>&1 && \\
echo "-= STAGE 2 =-" && \\
nice mencoder %(pass2opts)s -force-avi-aspect %(aspect)s %(input)s -o %(output)s 2>&1
""" %opts
